TARGET = firmware
NUCLEI_SDK_ROOT = ../../nuclei-sdk
# Remove comment if using macOS and toolchain was installed from Homebrew
COMPILE_PREFIX = riscv64-unknown-elf-
# GDB_UPLOAD_ARGS += -data-directory=/usr/local/Cellar/gdb/10.2/share/gdb
SRCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
