TARGET = firmware
#NUCLEI_SDK_ROOT = ../../nuclei-sdk
NUCLEI_SDK_ROOT = ../../nuclei-sdk-tuupola
SRCDIRS = . lib/hagl/src lib/hagl_hal/src
INCDIRS = . lib/hagl/include lib/hagl_hal/include
COMMON_FLAGS += -DHAGL_HAL_USE_DOUBLE_BUFFER #-include ./hagl_hal_config.h

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
